# Generated by Django 3.2 on 2021-08-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_general_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general_info',
            options={'verbose_name_plural': 'General info'},
        ),
        migrations.AddField(
            model_name='project',
            name='subheading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
