# Generated by Django 3.2 on 2021-08-29 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_subheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subheading',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
