# Generated by Django 3.2 on 2021-08-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_subheading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subheading',
        ),
    ]
