# Generated by Django 3.2 on 2021-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.ImageField(null=True, upload_to='media/')),
                ('name', models.CharField(max_length=25, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('contact_number_ext', models.CharField(max_length=3, null=True)),
                ('contact_number', models.CharField(max_length=9, null=True)),
                ('summary', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_icon', models.ImageField(null=True, upload_to='media/')),
                ('position', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('responsibilities', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_image', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
    ]
