# Generated by Django 3.2 on 2021-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='contact_email',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
