# Generated by Django 3.2 on 2021-08-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='chk', max_length=25),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(default='chk', max_length=50),
        ),
    ]
