# Generated by Django 3.2 on 2021-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210825_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='contact_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='summary',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
